apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.componentName }}
  title: ${{ values.componentName }}
  {%- if values.description %}
  description: ${{ values.description }}
  {%- endif %}
  annotations:
    # Kubernetes Integration
    {%- if values.kubernetesId %}
    backstage.io/kubernetes-id: ${{ values.kubernetesId }}
    {%- endif %}

    # Jira Integration
    {%- if values.jiraProjectKey %}
    jira/project-key: ${{ values.jiraProjectKey }}
    {%- endif %}

    # JFrog Artifactory Integration
    {%- if values.jfrogImage %}
    jfrog-artifactory/image-name: ${{ values.jfrogImage }}
    {%- endif %}

    # ArgoCD Integration
    {%- if values.argocdAppName %}
    argocd/app-name: ${{ values.argocdAppName }}
    {%- endif %}
    {%- if values.argocdAppSelector %}
    argocd/app-selector: ${{ values.argocdAppSelector }}
    {%- endif %}
  
  tags:
    - on-boarded
spec:
  type: service
  lifecycle: ${{ values.lifecycle }}
  owner: ${{ values.owner }}
  {%- if values.registerApi %}
  providesApis:
    - ${{ values.componentName }}-api
  {%- endif %}

{% if values.registerApi -%}
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.componentName }}-api
  title: ${{ values.componentName }} API
  description: API definition for ${{ values.componentName }}
  tags:
    - on-boarded
spec:
  type: ${{ values.apiType }}
  lifecycle: ${{ values.lifecycle }}
  owner: ${{ values.owner }}
  definition:
    $text: ${{ values.apiPath }}
{%- endif %}
